# .gitlab-ci.yml

# Define the stages: build -> deploy
stages:
  - build
  - deploy

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/
    - packages/**/node_modules/

# Define the image to be used for CI
image: node:20

# Set environment variables during the build stage:
variables:
  VITE_BASE_URL: https://api.edocs.laoit.dev

# Build stage to install dependencies and build the static site
build:
  stage: build
  script:
    - yarn -W --frozen-lockfile # Install dependencies
    - yarn workspace react build # Ensure running the build script inside 'react' workspace
  artifacts:
    paths:
      - 'packages/**/dist/' # Ensure this directory is where Vite outputs the build artifacts

# Deploy to GitLab Pages in the /public directory
pages:
  stage: deploy
  script:
    - mv packages/**/dist public/
  artifacts:
    paths:
      - public/ # GitLab Pages will serve content from the 'public' directory